---
network: true
vk_network: true

slides:
  - block:
    - photo_src: /img/title/photo_small_1.jpg
      before_src: /img/title/before_small_1.jpg
      after_src: /img/title/after_small_1.jpg
      block_active: true

    - photo_src: /img/title/photo_small_2.jpg
      before_src: /img/title/before_small_2.jpg
      after_src: /img/title/after_small_2.jpg

    - photo_src: /img/title/photo_small_3.jpg
      before_src: /img/title/before_small_3.jpg
      after_src: /img/title/after_small_3.jpg

    active: true

  - block:
    - photo_src: /img/title/photo_small_4.jpg
      before_src: /img/title/before_small_4.jpg
      after_src: /img/title/after_small_4.jpg
      block_active: true

    - photo_src: /img/title/photo_small_5.jpg
      before_src: /img/title/before_small_5.jpg
      after_src: /img/title/after_small_5.jpg

    - photo_src: /img/title/photo_small_6.jpg
      before_src: /img/title/before_small_6.jpg
      after_src: /img/title/after_small_6.jpg

cake_list:

  - src: http://files.fotonatorte.ru/cake_image_4f4769b571904.jpg
    price: 1390
    price_was: 1700
    weight: 1

  - src: http://files.fotonatorte.ru/cake_image_4f2be1b0f23b5.jpg
    price: 1390
    price_was: 1700
    weight: 1

  - src: http://files.fotonatorte.ru/cake_image_4f476e4e9c0bb.jpg
    price: 1390
    price_was: 1700
    weight: 1


  - src: http://files.fotonatorte.ru/cake_image_4f476fd6a7e44.jpg
    price: 1390
    price_was: 1700
    weight: 1

  - src: http://files.fotonatorte.ru/cake_image_4f4771f5912c3.jpg
    price: 1390
    price_was: 1700
    weight: 1

  - src: http://files.fotonatorte.ru/cake_image_4f47724f95008.jpg
    price: 1390
    price_was: 1700
    weight: 1


  - src: http://files.fotonatorte.ru/cake_image_4f2bcf835adb9.jpg
    price: 1390
    price_was: 1700
    weight: 1

  - src: http://files.fotonatorte.ru/cake_image_4f4775c3b1667.jpg
    price: 1390
    price_was: 1700
    weight: 1

  - src: http://files.fotonatorte.ru/cake_image_4f2bd57a52b6e.jpg
    price: 1490
    price_was: 3000
    weight: 2
---